
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/rede_sigma
    username: postgres
    password: changemeinprod!
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5433/rede_sigma
    user: postgres
    password: changemeinprod! 
    baseline-on-migrate: true
    
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  
  server:
    servlet:
      context-path: /